# code: language=ansible
---
- name: Install applications
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - base
    - bash
    - chrome
    - vs_code
    - docker
    - yt-dlp
- name: Install configurations
  hosts: localhost
  roles:
    - bash
  tags:
    - configuration
