---
- name: Import Google Chrome GPG signing key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
    id: 7FAC5991

- name: Add Google Chrome x86_64 repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
  when: ansible_architecture == 'x86_64'

- name: Install Google Chrome
  ansible.builtin.apt:
    pkg: google-chrome-stable
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: google_chrome_install
