---
- name: Install apt based packages
  ansible.builtin.apt:
    name:
      - gnupg2
      - openssh-server
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnome-shell-extension-manager
      - git
      - mc
      - vim
      - wireguard
      - curl
      - notepadqq
      - ffmpeg
      - normalize-audio
      - wodim # cdrecord
      - vlc
    cache_valid_time: 3600
    update_cache: true
    state: present
